name: os-ci

on: 
  workflow_dispatch:
  pull_request:
      branches:
        - develop
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        max-parallel: 2
        matrix:
          uses: [actions/checkout@v1]
          name: [python-version]
          python-version: [3.8, 3.9]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: python opensolar_ci/manage.py migrate
    - name: Run tests
      run: python opensolar_ci/manage.py test
